services:
  ctf-instance-runner:
    build: .
    ports:
      - "${RUNNER_PORT}:80"
    environment:
      - FLASK_ENV=production
      - DOMAIN=${DOMAIN}
      - DURATION=${DURATION}
      - CHALL_PORT_RANGE_START=${CHALL_PORT_RANGE_START}
      - CHALL_PORT_RANGE_END=${CHALL_PORT_RANGE_END}
      - RUNNER_PORT=${RUNNER_PORT}
      - CHALL_TITLE=${CHALL_TITLE}
    volumes:
      - /tmp:/tmp # Share /tmp for instance management
      - ./chall:/app/chall # Mount challenge scripts from host
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-in-Docker
    restart: unless-stopped
